"""PostToolUse: rebuild docs/decisions/README.md — a one-line-per-ADR
index (id, title, status, supersedes/superseded-by) — whenever an ADR
is written or edited. Lets an agent see what decisions exist and their
status without opening or globbing every file. Writes the filesystem
directly (not through the Write/Edit tool), so it never re-triggers
itself or the ADR immutability guard.
"""
import glob
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _project_paths import hook_should_run, normalize, read_hook_input, resolve_docs_root  # noqa: E402


def parse_adr(path: str):
    try:
        with open(path, encoding="utf-8") as f:
            content = f.read()
    except FileNotFoundError:
        return None

    # Only look inside the YAML frontmatter block — an ADR's body can
    # otherwise contain lines that look like frontmatter fields (e.g.
    # discussing an HTTP "status:" code) and get matched by mistake.
    fm_match = re.match(r"^---\n(.*?)\n---", content, re.DOTALL)
    frontmatter = fm_match.group(1) if fm_match else ""

    id_match = re.search(r"^id:\s*(\d{4})", frontmatter, re.MULTILINE)
    status_match = re.search(r"^status:\s*(\S+)", frontmatter, re.MULTILINE)
    supersedes_match = re.search(r"^supersedes:\s*(\S+)", frontmatter, re.MULTILINE)
    superseded_by_match = re.search(r"^superseded_by:\s*(\S+)", frontmatter, re.MULTILINE)
    title_match = re.search(r"^#\s*ADR\s*\d+\s*[—-]\s*(.+)$", content, re.MULTILINE)

    if not id_match:
        return None

    def clean(m, default="—"):
        if not m:
            return default
        v = m.group(1).strip()
        return default if v in ("null", "~", "") else v

    return {
        "id": id_match.group(1),
        "status": clean(status_match, "unknown"),
        "supersedes": clean(supersedes_match),
        "superseded_by": clean(superseded_by_match),
        "title": title_match.group(1).strip() if title_match else "(untitled)",
        "file": os.path.basename(path),
    }


def main() -> None:
    # Registration gate (ADR 0017): a no-op for an unregistered repo under
    # a user-level install; always open in modes A/B.
    if not hook_should_run(os.environ.get("CLAUDE_PROJECT_DIR", ".")):
        return

    data = read_hook_input()
    path = data.get("tool_input", {}).get("file_path", "") or data.get("tool_response", {}).get("filePath", "")
    if not path:
        return

    project = os.environ.get("CLAUDE_PROJECT_DIR", ".")
    abspath = path if os.path.isabs(path) else os.path.join(project, path)
    decisions_dir = os.path.join(resolve_docs_root(project), "decisions")

    # Self-gating: this hook fires on every Write/Edit in the multi-project
    # settings variant, so it decides relevance itself rather than trusting
    # a literal-prefix `if` condition — it compares the tool-reported
    # path's own directory against the resolved decisions_dir directly
    # instead, which works regardless of which of the two path shapes a
    # tool call reports (see resolve_docs_root in _project_paths.py).
    if normalize(os.path.dirname(abspath)) != normalize(decisions_dir):
        return
    if os.path.basename(abspath) == "README.md":
        return

    entries = []
    for candidate in sorted(glob.glob(os.path.join(decisions_dir, "[0-9][0-9][0-9][0-9]-*.md"))):
        if os.path.basename(candidate).startswith("0000-"):
            continue  # reserved for the blank copyable template
        entry = parse_adr(candidate)
        if entry:
            entries.append(entry)
    entries.sort(key=lambda e: e["id"])

    lines = [
        "<!-- Auto-generated by decision_index.py — do not edit by hand. -->",
        "",
        "# Architecture decisions — index",
        "",
        "One line per ADR. Open the file only if the summary here doesn't",
        "already answer your question — see the `adr-writing` skill for the",
        "format.",
        "",
        "| ID | Title | Status | Supersedes | Superseded by |",
        "|---|---|---|---|---|",
    ]
    for e in entries:
        lines.append(
            f"| {e['id']} | [{e['title']}]({e['file']}) | {e['status']} | {e['supersedes']} | {e['superseded_by']} |"
        )

    with open(os.path.join(decisions_dir, "README.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(json.dumps({"systemMessage": f"docs/decisions/README.md index refreshed ({len(entries)} ADRs)."}))


if __name__ == "__main__":
    main()
