"""SessionEnd: snapshot the session's last assistant message as a
handoff note, so the next SessionStart's brief can show more than just
git status. Deterministic, zero token cost — no transcript parsing, no
LLM call. Relies on this framework's own convention (see the top-level
system instructions this project's agents run under) that a turn ends
with a short "what changed and what's next" summary, so the last
assistant message is usually already a reasonable handoff note.

Overwrites (not appends) — only the latest handoff matters; an
unbounded log would itself need the same context-budget discipline
this framework asks of every other doc.
"""
import json
import os
import sys
from datetime import datetime, timezone

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _project_paths import state_file_path  # noqa: E402

HANDOFF_FILENAME = "session-handoff.md"


def main() -> None:
    data = json.load(sys.stdin)
    message = (data.get("last_assistant_message") or "").strip()
    if not message:
        return

    project = os.environ.get("CLAUDE_PROJECT_DIR", ".")
    end_reason = data.get("end_reason", "unknown")
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    content = (
        f"<!-- Auto-generated by .claude/hooks/session_handoff.py — do not edit by hand. -->\n"
        f"<!-- Overwritten at the end of every session; add this file to .gitignore — "
        f"it's per-machine operational state, not project documentation. -->\n\n"
        f"# Last session handoff\n\n"
        f"Ended: {timestamp} ({end_reason})\n\n"
        f"{message}\n"
    )

    # Per-project state, not `.claude/` machinery: with a shared
    # `.claude/` this would otherwise be one physical file for every
    # target repo (ADR 0013), so it follows the project, not the config
    # directory. session_brief.py reads back from the same resolution.
    with open(state_file_path(project, HANDOFF_FILENAME), "w", encoding="utf-8") as f:
        f.write(content)


if __name__ == "__main__":
    main()
