"""PostToolUse: rebuild .claude/skills/README.md — a one-line-per-skill
index (name, which agents it's tagged for, description) — whenever a
SKILL.md is written or edited. Lets an agent check what skills exist
and which apply to it without opening or globbing every SKILL.md.
Writes the filesystem directly (not through the Write/Edit tool), so
it never re-triggers itself.
"""
import glob
import json
import os
import re
import sys


def parse_skill(path: str):
    try:
        with open(path, encoding="utf-8") as f:
            content = f.read()
    except FileNotFoundError:
        return None

    # Only look inside the YAML frontmatter block — a skill's body (e.g.
    # skill-authoring's own template example) can otherwise contain lines
    # that look like frontmatter fields and get matched by mistake.
    fm_match = re.match(r"^---\n(.*?)\n---", content, re.DOTALL)
    frontmatter = fm_match.group(1) if fm_match else ""

    name_match = re.search(r"^name:\s*(\S+)", frontmatter, re.MULTILINE)
    desc_match = re.search(r"^description:\s*(.+)$", frontmatter, re.MULTILINE)
    applies_match = re.search(r"^applies_to:\s*\[(.*?)\]", frontmatter, re.MULTILINE)

    if not name_match:
        return None

    applies_to = []
    if applies_match:
        applies_to = [a.strip() for a in applies_match.group(1).split(",") if a.strip()]

    return {
        "name": name_match.group(1).strip(),
        "description": desc_match.group(1).strip() if desc_match else "",
        "applies_to": applies_to,
        "dir": os.path.basename(os.path.dirname(path)),
    }


def main() -> None:
    data = json.load(sys.stdin)
    path = data.get("tool_input", {}).get("file_path", "") or data.get("tool_response", {}).get("filePath", "")
    if not path:
        return

    project = os.environ.get("CLAUDE_PROJECT_DIR", ".")
    abspath = path if os.path.isabs(path) else os.path.join(project, path)
    normalized = abspath.replace("\\", "/")

    # `.claude/skills` may be a real/symlinked project directory (mode A/B)
    # or, when the project itself has no `.claude` at all (mode C), only
    # exist at the user-level `~/.claude/skills` — check both candidates,
    # since the path reported here can be relative or an absolute mode-C
    # path with no relationship to `project` at all.
    candidates = [
        os.path.join(project, ".claude", "skills"),
        os.path.join(os.path.expanduser("~"), ".claude", "skills"),
    ]
    skills_dir = None
    for candidate in candidates:
        normalized_candidate = candidate.replace("\\", "/").rstrip("/")
        if normalized.startswith(normalized_candidate + "/"):
            skills_dir = candidate
            break
    if skills_dir is None:
        return
    if os.path.basename(abspath) != "SKILL.md":
        return

    entries = []
    for candidate in sorted(glob.glob(os.path.join(skills_dir, "*", "SKILL.md"))):
        entry = parse_skill(candidate)
        if entry:
            entries.append(entry)
    entries.sort(key=lambda e: e["name"])

    lines = [
        "<!-- Auto-generated by .claude/hooks/skill_index.py — do not edit by hand. -->",
        "",
        "# Skills — index",
        "",
        "One line per skill. `Applies to` lists which `.claude/agents/*.md`",
        "roles it's most relevant to (from the skill's own `applies_to`",
        "frontmatter, e.g. `applies_to: [coder, reviewer]`) — an agent should",
        "check here for entries tagged with its own name before starting a",
        "task. A skill with no tag isn't scoped to one pipeline role (e.g. a",
        "meta-skill about the framework itself).",
        "",
        "| Skill | Applies to | Description |",
        "|---|---|---|",
    ]
    for e in entries:
        applies = ", ".join(e["applies_to"]) if e["applies_to"] else "—"
        lines.append(f"| [{e['name']}]({e['dir']}/SKILL.md) | {applies} | {e['description']} |")

    with open(os.path.join(skills_dir, "README.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(json.dumps({"systemMessage": f".claude/skills/README.md index refreshed ({len(entries)} skills)."}))


if __name__ == "__main__":
    main()
