"""PostToolUse: rebuild .claude/skills/README.md — a one-line-per-skill
index (name, which agents it's tagged for, description) — whenever a
SKILL.md is written or edited. Lets an agent check what skills exist
and which apply to it without opening or globbing every SKILL.md.
Writes the filesystem directly (not through the Write/Edit tool), so
it never re-triggers itself.

Scope (framework ADR 0017, framework spec 0001 D3): this hook only ever reads and writes the
framework's own skills. In modes A/B that is `<project>/.claude/skills/`.
In a user-level install it is the `<prefix>-*` folders under the config
directory's `skills/`, and the index is written inside the install
namespace (`framework.json` → `skills_index`). A user's personal skills
beside them are never globbed, and nothing is written into the user's
own `skills/` folder.
"""
import fnmatch
import glob
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _project_paths import framework_config, hook_should_run, normalize, read_hook_input  # noqa: E402


def parse_skill(path: str):
    try:
        with open(path, encoding="utf-8") as f:
            content = f.read()
    except FileNotFoundError:
        return None

    # Only look inside the YAML frontmatter block — a skill's body (e.g.
    # skill-authoring's own template example) can otherwise contain lines
    # that look like frontmatter fields and get matched by mistake.
    fm_match = re.match(r"^---\n(.*?)\n---", content, re.DOTALL)
    frontmatter = fm_match.group(1) if fm_match else ""

    name_match = re.search(r"^name:\s*(\S+)", frontmatter, re.MULTILINE)
    desc_match = re.search(r"^description:\s*(.+)$", frontmatter, re.MULTILINE)
    applies_match = re.search(r"^applies_to:\s*\[(.*?)\]", frontmatter, re.MULTILINE)

    if not name_match:
        return None

    applies_to = []
    if applies_match:
        applies_to = [a.strip() for a in applies_match.group(1).split(",") if a.strip()]

    return {
        "name": name_match.group(1).strip(),
        "description": desc_match.group(1).strip() if desc_match else "",
        "applies_to": applies_to,
        "dir": os.path.basename(os.path.dirname(path)),
    }


def skill_scope(project: str):
    """`(skills_dir, folder_glob, index_path)` for this install, per the
    module docstring's scope rule.
    """
    config = framework_config()
    if config.get("install_mode") == "user-level":
        prefix = config.get("prefix") or ""
        skills_dir = config.get("skills_dir") or os.path.join(config.get("config_dir", ""), "skills")
        index_path = config.get("skills_index") or os.path.join(config.get("namespace_dir", ""), "skills-index.md")
        return skills_dir, (prefix + "-*") if prefix else "*", index_path
    skills_dir = os.path.join(project, ".claude", "skills")
    return skills_dir, "*", os.path.join(skills_dir, "README.md")


def write_index(skills_dir: str, folder_glob: str, index_path: str) -> int:
    """Rebuild the index from every `<skills_dir>/<folder_glob>/SKILL.md`.
    Returns the number of skills indexed. Also used by the user-level
    installer to write the first index.
    """
    entries = []
    for candidate in sorted(glob.glob(os.path.join(skills_dir, folder_glob, "SKILL.md"))):
        entry = parse_skill(candidate)
        if entry:
            entry["link"] = normalize(os.path.relpath(candidate, os.path.dirname(index_path)))
            entries.append(entry)
    entries.sort(key=lambda e: e["name"])

    lines = [
        "<!-- Auto-generated by skill_index.py — do not edit by hand. -->",
        "",
        "# Skills — index",
        "",
        "One line per skill. `Applies to` lists which agent roles it's most",
        "relevant to (from the skill's own `applies_to` frontmatter, e.g.",
        "`applies_to: [coder, reviewer]`) — an agent should check here for",
        "entries tagged with its own name before starting a task. A skill with",
        "no tag isn't scoped to one pipeline role (e.g. a meta-skill about the",
        "framework itself).",
        "",
        "| Skill | Applies to | Description |",
        "|---|---|---|",
    ]
    for e in entries:
        applies = ", ".join(e["applies_to"]) if e["applies_to"] else "—"
        lines.append(f"| [{e['name']}]({e['link']}) | {applies} | {e['description']} |")

    os.makedirs(os.path.dirname(index_path), exist_ok=True)
    with open(index_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    return len(entries)


def main() -> None:
    # Registration gate (framework ADR 0017): a no-op for an unregistered repo under
    # a user-level install; always open in modes A/B.
    if not hook_should_run(os.environ.get("CLAUDE_PROJECT_DIR", ".")):
        return

    data = read_hook_input()
    path = data.get("tool_input", {}).get("file_path", "") or data.get("tool_response", {}).get("filePath", "")
    if not path:
        return

    project = os.environ.get("CLAUDE_PROJECT_DIR", ".")
    abspath = path if os.path.isabs(path) else os.path.join(project, path)
    if os.path.basename(abspath) != "SKILL.md":
        return

    skills_dir, folder_glob, index_path = skill_scope(project)
    # Only a SKILL.md directly inside one of this framework's own skill
    # folders counts — never a personal skill that merely sits beside them.
    skill_folder = os.path.dirname(abspath)
    if normalize(os.path.dirname(skill_folder)) != normalize(skills_dir):
        return
    if not fnmatch.fnmatch(os.path.basename(skill_folder), folder_glob):
        return

    count = write_index(skills_dir, folder_glob, index_path)
    print(json.dumps({"systemMessage": f"Skills index refreshed ({count} skills): {normalize(index_path)}"}))


if __name__ == "__main__":
    main()
