"""PostToolUse: rebuild docs/product/specs/README.md — a one-line-per-spec
index (id, title, area, status, related specs) — whenever a spec is
written or edited. Lets an agent see what specs exist, their status,
and their lineage (see framework ADR 0008)
without opening or globbing every file. Writes the filesystem directly
(not through the Write/Edit tool), so it never re-triggers itself.

One row per spec across the layouts (framework ADR 0024 section 3): a
folder's row is titled from its `spec.md` and links to it; a legacy file's
row is unchanged. When the same edit makes a status flip due,
`spec_status_sync.py` flips and rebuilds in process, so this hook stays
silent. `rebuild(project_dir)` is importable for that.
"""
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import _spec_layout  # noqa: E402
from _project_paths import hook_should_run, normalize, read_hook_input, resolve_shared_docs_root, specs_dir as project_specs_dir  # noqa: E402


def title_from_filename(basename: str) -> str:
    stem = re.sub(r"^\d{4}-", "", basename)
    stem = re.sub(r"\.md$", "", stem)
    words = stem.replace("-", " ").replace("_", " ")
    return words[:1].upper() + words[1:] if words else "(untitled)"


def parse_spec(ref: dict):
    """One index row from a resolver reference: from `spec.md` (or the
    single file), or `unknown` for a folder that has no `spec.md` yet.
    """
    entry = ref["folder"] or ref["spec_file"]
    name = os.path.basename(entry)
    spec_file = ref["spec_file"]
    content = _spec_layout.read_text(spec_file) if spec_file else ""

    # Only look inside the YAML frontmatter block — a spec's body can
    # otherwise contain lines that look like frontmatter fields and get
    # matched by mistake.
    fm = _spec_layout.frontmatter(content)

    id_match = re.match(r"\d{4}", fm.get("id", ""))
    heading_match = re.search(r"^#\s+(.+)$", content, re.MULTILINE)

    heading = heading_match.group(1).strip() if heading_match else ""
    title = heading if heading and heading.lower() != "feature name" else title_from_filename(name)

    area = fm.get("area", "").strip()
    related_ids = re.findall(r"\d{4}", fm.get("relates_to", ""))

    if ref["folder"]:
        link = f"{name}/spec.md" if spec_file else f"{name}/"
    else:
        link = name

    return {
        "id": id_match.group(0) if id_match else name[:4],
        "status": fm.get("status", "").strip() or "unknown",
        "area": area if area else "(unassigned)",
        "related": related_ids,
        "title": title,
        "file": link,
    }


def shared_doc_ref(project: str, from_dir: str, shared_relpath: str, label: str) -> str:
    """A reference to shared framework material, relative to where the
    index actually sits (framework spec 0001 D4). The index lives in a project
    subtree in modes B/C, and the shared root sits elsewhere, so a fixed
    `../../decisions/...` only resolves in mode A. Falls back to a plain
    label when the target isn't on disk, never a dead path.
    """
    shared = resolve_shared_docs_root(project)
    if shared:
        target = os.path.join(shared, *shared_relpath.split("/"))
        if os.path.isfile(target):
            try:
                rel = normalize(os.path.relpath(target, from_dir))
            except ValueError:  # different drive on Windows
                rel = normalize(target)
            return f"`{rel}`"
    return label


def rebuild(project: str) -> str:
    """Rewrite the specs README.md index for `project` and return the
    one-line summary message.
    """
    specs_dir = project_specs_dir(project)
    entries = []
    for ref in _spec_layout.iter_specs(specs_dir):
        entry = ref["folder"] or ref["spec_file"]
        if ".validation-" in os.path.basename(entry):
            continue
        entries.append(parse_spec(ref))
    entries.sort(key=lambda e: (e["area"], e["id"]))

    # Framework ADRs live in the framework repository (evolution/), never in
    # a project: name it, don't link it — a project's own decisions/0008-*
    # is an unrelated document with a colliding number.
    lineage_adr = "framework ADR 0008"
    template = shared_doc_ref(project, specs_dir, "product/requirements-template.md", "the requirements template")
    lines = [
        "<!-- Auto-generated by spec_index.py — do not edit by hand. -->",
        "",
        "# Product specs — index",
        "",
        f"One line per spec, grouped by area (see {lineage_adr}). Open the",
        "file only if the summary here doesn't already answer your question —",
        f"see {template} for the format. `/spec` reads this table to infer a",
        "new spec's own `area`/`relates_to` automatically.",
        "",
        "| ID | Title | Area | Status | Related to |",
        "|---|---|---|---|---|",
    ]
    for e in entries:
        related = ", ".join(e["related"]) if e["related"] else "—"
        lines.append(f"| {e['id']} | [{e['title']}]({e['file']}) | {e['area']} | {e['status']} | {related} |")

    os.makedirs(specs_dir, exist_ok=True)
    with open(os.path.join(specs_dir, "README.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    areas = len({e["area"] for e in entries})
    return f"docs/product/specs/README.md index refreshed ({len(entries)} specs, {areas} area(s))."


def main() -> None:
    # Registration gate (framework ADR 0017): a no-op for an unregistered repo under
    # a user-level install; always open in modes A/B.
    if not hook_should_run(os.environ.get("CLAUDE_PROJECT_DIR", ".")):
        return

    data = read_hook_input()
    path = data.get("tool_input", {}).get("file_path", "") or data.get("tool_response", {}).get("filePath", "")
    if not path:
        return

    project = os.environ.get("CLAUDE_PROJECT_DIR", ".")
    abspath = path if os.path.isabs(path) else os.path.join(project, path)
    if ".validation-" in os.path.basename(abspath):
        return

    # Self-gating: this hook fires on every Write/Edit in the multi-project
    # settings variant, so the resolver decides relevance (a spec file or any
    # file inside a spec folder, at the right depth) instead of a literal-prefix
    # `if` condition.
    ref = _spec_layout.classify(project_specs_dir(project), abspath)
    if ref is None:
        return

    # One index writer per flip: when this edit makes the status flip due,
    # spec_status_sync.py flips and rebuilds in process.
    import spec_status_sync  # noqa: E402  (imports this module; kept lazy)
    if ref["role"] in ("spec", "tasks") and spec_status_sync.flip_due(ref):
        return

    print(json.dumps({"systemMessage": rebuild(project)}))


if __name__ == "__main__":
    main()
