"""PostToolUse: rebuild docs/product/specs/README.md — a one-line-per-spec
index (id, title, area, status, related specs) — whenever a spec is
written or edited. Lets an agent see what specs exist, their status,
and their lineage (see docs/decisions/0008-spec-area-lineage.md)
without opening or globbing every file. Writes the filesystem directly
(not through the Write/Edit tool), so it never re-triggers itself.
"""
import glob
import json
import os
import re
import sys


def title_from_filename(basename: str) -> str:
    stem = re.sub(r"^\d{4}-", "", basename)
    stem = re.sub(r"\.md$", "", stem)
    words = stem.replace("-", " ").replace("_", " ")
    return words[:1].upper() + words[1:] if words else "(untitled)"


def parse_spec(path: str):
    try:
        with open(path, encoding="utf-8") as f:
            content = f.read()
    except FileNotFoundError:
        return None

    # Only look inside the YAML frontmatter block — a spec's body can
    # otherwise contain lines that look like frontmatter fields and get
    # matched by mistake.
    fm_match = re.match(r"^---\n(.*?)\n---", content, re.DOTALL)
    frontmatter = fm_match.group(1) if fm_match else ""

    id_match = re.search(r"^id:\s*(\d{4})", frontmatter, re.MULTILINE)
    status_match = re.search(r"^status:\s*(.+)$", frontmatter, re.MULTILINE)
    area_match = re.search(r"^area:\s*(.+)$", frontmatter, re.MULTILINE)
    relates_match = re.search(r"^relates_to:\s*(.+)$", frontmatter, re.MULTILINE)
    heading_match = re.search(r"^#\s+(.+)$", content, re.MULTILINE)

    basename = os.path.basename(path)
    spec_id = id_match.group(1) if id_match else basename[:4]

    heading = heading_match.group(1).strip() if heading_match else ""
    title = heading if heading and heading.lower() != "feature name" else title_from_filename(basename)

    area = area_match.group(1).strip() if area_match else ""
    related_ids = re.findall(r"\d{4}", relates_match.group(1)) if relates_match else []

    return {
        "id": spec_id,
        "status": status_match.group(1).strip() if status_match else "unknown",
        "area": area if area else "(unassigned)",
        "related": related_ids,
        "title": title,
        "file": basename,
    }


def main() -> None:
    data = json.load(sys.stdin)
    path = data.get("tool_input", {}).get("file_path", "") or data.get("tool_response", {}).get("filePath", "")
    if not path:
        return

    project = os.environ.get("CLAUDE_PROJECT_DIR", ".")
    abspath = path if os.path.isabs(path) else os.path.join(project, path)
    specs_dir = os.path.join(project, "docs", "product", "specs")

    normalized_dir = os.path.dirname(abspath).replace("\\", "/").rstrip("/")
    if normalized_dir != specs_dir.replace("\\", "/").rstrip("/"):
        return
    if os.path.basename(abspath) == "README.md":
        return

    entries = []
    for candidate in sorted(glob.glob(os.path.join(specs_dir, "[0-9][0-9][0-9][0-9]-*.md"))):
        if ".validation-" in os.path.basename(candidate):
            continue
        entry = parse_spec(candidate)
        if entry:
            entries.append(entry)
    entries.sort(key=lambda e: (e["area"], e["id"]))

    lines = [
        "<!-- Auto-generated by .claude/hooks/spec_index.py — do not edit by hand. -->",
        "",
        "# Product specs — index",
        "",
        "One line per spec, grouped by area (see",
        "`../../decisions/0008-spec-area-lineage.md`). Open the file only if",
        "the summary here doesn't already answer your question — see",
        "`../requirements-template.md` for the format. `/spec` reads this table",
        "to infer a new spec's own `area`/`relates_to` automatically.",
        "",
        "| ID | Title | Area | Status | Related to |",
        "|---|---|---|---|---|",
    ]
    for e in entries:
        related = ", ".join(e["related"]) if e["related"] else "—"
        lines.append(f"| {e['id']} | [{e['title']}]({e['file']}) | {e['area']} | {e['status']} | {related} |")

    with open(os.path.join(specs_dir, "README.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    areas = len({e["area"] for e in entries})
    print(json.dumps({"systemMessage": f"docs/product/specs/README.md index refreshed ({len(entries)} specs, {areas} area(s))."}))


if __name__ == "__main__":
    main()
